[package]
name = "vetkd_testing_canister"
version = "0.2.0"
edition = "2021"

resolver = "2"

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
candid = "0.10.14"
ic-cdk = "0.18.2-alpha.1"
